spring:
  application:
    name: reciping-ads-service-BE
  datasource:
    url: jdbc:postgresql://reciping-rdb.c7wokrloy1td.ap-northeast-2.rds.amazonaws.com:15432/reciping_postgres_ad
    username: postgres
    password: changeme
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      indent_output: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

cloud:
  aws:
    s3:
      bucket: reciping-be
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health